{{- range .Values.projects }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "caCertName" . }}
spec:
  isCA: true
  commonName: {{ .ca.name }}
  duration: {{ .ca.duration }}
  renewBefore: {{ .ca.renewBefore }}
  secretName: {{ include "caSecretName" . }}
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: {{ include "issuerName" . }}
    kind: Issuer
    group: cert-manager.io
---
{{- end }}