{{- range .Values.projects }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "caIssuerName" . }}
  namespace: {{ $.Values.namespace }}
  
spec:
  ca:
    secretName: {{ include "caSecretName" . }}
---
{{- end }}