apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronJob.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.cronJob.serviceAccount }}
          containers:
          - name: "{{ .Values.cronJob.name }}-container"
            image: {{ .Values.cronJob.image }}
            imagePullPolicy: IfNotPresent
            command:
            - sh
            - -c
            - gcloud container clusters get-credentials cluster-1 --region europe-west2 --project playpen-3a83c0 && python3 update-k8s-gcp-cert-secret.py --expiry=24
          restartPolicy: OnFailure
