apiVersion: batch/v1
kind: CronJob
metadata:
  name: every-10-mins-job
spec:
  schedule: "*/10 * * * *"  # This schedule runs the job every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-container
            image: busybox
            command: ["sh", "-c", "echo Hello, Kubernetes!"]
          restartPolicy: OnFailure