apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cronJob.serviceAccount }}
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: svc-gke-secret-sync@playpen-3a83c0.iam.gserviceaccount.com