apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cronJob.serviceAccount }}
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: svc-gke-gcp-secret-sync@playpen-86bd2a.iam.gserviceaccount.com